services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=philoagents
      - MONGODB_INITDB_ROOT_PASSWORD=philoagents
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - philoagents-network
  api:
    profiles: [python]
    container_name: philoagents-api
    build:
      context: ./philoagents-api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-api/.env
    networks:
      - philoagents-network
  java-api:
    profiles: [java]
    container_name: philoagents-java-api
    build:
      context: ./philoagents-java-api
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://philoagents:philoagents@local_dev_atlas:27017/?directConnection=true
    ports:
      - "8000:8000"
    env_file:
      - ./philoagents-java-api/.env      
    networks:
      - philoagents-network    
  ui:
    container_name: philoagents-ui
    build:
      context: ./philoagents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./philoagents-ui:/app
      - /app/node_modules
    depends_on:
      - java-api
    networks:
      - philoagents-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./philoagents-java-api/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"      
    networks:
      - philoagents-network      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./philoagents-java-api/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./philoagents-java-api/monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/ai-metrics-dashboard.json
    depends_on:
      - prometheus      
    networks:
      - philoagents-network      

volumes:
  data:
  config:
  grafana-storage:

networks:
  philoagents-network:
    name: philoagents-network